// <auto-generated />
using System;
using LandProperty.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandProperty.Data.Migrations
{
    [DbContext(typeof(LandPropertyContext))]
    [Migration("20251108105257_Extracted data string value increase")]
    partial class Extracteddatastringvalueincrease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandProperty.Data.Models.Bids.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<decimal>("BidAmountByOwner")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BidAmountByUser")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.Property<int?>("LandId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PurchaseRequest")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BidId");

                    b.HasIndex("HomeId");

                    b.HasIndex("LandId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Logger", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Loggers");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerHome.HomeDocuments", b =>
                {
                    b.Property<int>("HomeDocumnetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeDocumnetsId"));

                    b.Property<string>("DocumentDetailsExtracted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.HasKey("HomeDocumnetsId");

                    b.HasIndex("HomeId");

                    b.ToTable("HomeDocuments");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerHome.OwnerHomeDetails", b =>
                {
                    b.Property<int>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeId"));

                    b.Property<decimal>("AreaInSqFt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeCity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HomeDiscription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HomePhoneno")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HomePincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HomePriceInital")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("HomeSellDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomeState")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HomeStatusApproved")
                        .HasColumnType("bit");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("OwnerHomeDetails");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerLand.LandDocumnets", b =>
                {
                    b.Property<int>("LandDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandDocumentId"));

                    b.Property<string>("DocumentDetailsExtracted")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int?>("LandId")
                        .HasColumnType("int");

                    b.HasKey("LandDocumentId");

                    b.HasIndex("LandId");

                    b.ToTable("LandDocuments");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerLand.OwnerLandDetails", b =>
                {
                    b.Property<int>("LandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandId"));

                    b.Property<string>("LandAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LandAreaInSqFt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LandCity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LandDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LandPhoneno")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LandPincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LandPriceInitial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("LandSellDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LandState")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LandStatusApproved")
                        .HasColumnType("bit");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LandId");

                    b.HasIndex("UserId");

                    b.ToTable("OwnerLandDetails");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Roles.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleTypeNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Roles.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UserBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoneNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LandProperty.Data.Models.UserHomeApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<decimal>("OfferedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationId");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHomeApplications");
                });

            modelBuilder.Entity("LandProperty.Data.Models.UserLandApllication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("LandId")
                        .HasColumnType("int");

                    b.Property<decimal>("OfferedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationId");

                    b.HasIndex("LandId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLandApplications");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Bids.Bid", b =>
                {
                    b.HasOne("LandProperty.Data.Models.OwnerHome.OwnerHomeDetails", "Home")
                        .WithMany("Bids")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LandProperty.Data.Models.OwnerLand.OwnerLandDetails", "Land")
                        .WithMany("Bids")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LandProperty.Data.Models.Roles.User", "User")
                        .WithMany("Bid")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("Land");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Logger", b =>
                {
                    b.HasOne("LandProperty.Data.Models.Roles.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerHome.HomeDocuments", b =>
                {
                    b.HasOne("LandProperty.Data.Models.OwnerHome.OwnerHomeDetails", "OwnerHomeDetails")
                        .WithMany("HomeDocuments")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OwnerHomeDetails");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerHome.OwnerHomeDetails", b =>
                {
                    b.HasOne("LandProperty.Data.Models.Roles.User", "User")
                        .WithMany("OwnerHomeDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerLand.LandDocumnets", b =>
                {
                    b.HasOne("LandProperty.Data.Models.OwnerLand.OwnerLandDetails", "OwnerLandDetails")
                        .WithMany("LandDocuments")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OwnerLandDetails");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerLand.OwnerLandDetails", b =>
                {
                    b.HasOne("LandProperty.Data.Models.Roles.User", "User")
                        .WithMany("OwnerLandDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Roles.User", b =>
                {
                    b.HasOne("LandProperty.Data.Models.Roles.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LandProperty.Data.Models.UserHomeApplication", b =>
                {
                    b.HasOne("LandProperty.Data.Models.OwnerHome.OwnerHomeDetails", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandProperty.Data.Models.Roles.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LandProperty.Data.Models.UserLandApllication", b =>
                {
                    b.HasOne("LandProperty.Data.Models.OwnerLand.OwnerLandDetails", "Land")
                        .WithMany()
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandProperty.Data.Models.Roles.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Land");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerHome.OwnerHomeDetails", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("HomeDocuments");
                });

            modelBuilder.Entity("LandProperty.Data.Models.OwnerLand.OwnerLandDetails", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("LandDocuments");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Roles.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LandProperty.Data.Models.Roles.User", b =>
                {
                    b.Navigation("Bid");

                    b.Navigation("OwnerHomeDetails");

                    b.Navigation("OwnerLandDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
